keys:
  - &system_lg_laptop age1yqsdglc9s03k6yhefaqpnpyurj0j9nktlccc8rq2uevpuzn0ea2stx0msr
  - &system_zephyrus age1ldzusjw28wzed8y6q9ynn9d7se7qxpsapxxys00jgrsfdw88eeasnt795x
  - &admin_soriphoono age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
  - &admin_spookyskelly age1kv7f5nyknwhf5lvm7yzhm0jetleceklj7u225uxce5x007hkvgys0fmeey
creation_rules:
  - path_regex: nix/homes/soriphoono(@[^/]+)?/[^/]+\.(yml|json|env|ini)$
    key_groups:
      - age:
          - *admin_soriphoono
  - path_regex: nix/homes/spookyskelly(@[^/]+)?/[^/]+\.(yml|json|env|ini)$
    key_groups:
      - age:
          - *admin_soriphoono
          - *admin_spookyskelly
  - path_regex: nix/systems/lg-laptop/[^/]+\.(yml|json|env|ini)$
    key_groups:
      - age:
          - *admin_soriphoono
          - *system_lg_laptop
  - path_regex: nix/systems/zephyrus/[^/]+\.(yml|json|env|ini)$
    key_groups:
      - age:
          - *admin_soriphoono
          - *system_zephyrus
