apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets-helmrepository.yaml
  - jetstack-helmrepository.yaml
  - hashicorp-helmrepository.yaml
  - longhorn-helmrepository.yaml
  - netbird-helmrepository.yaml
  - sealed-secrets-helmrepository.yaml
  - traefik-helmrepository.yaml
  - traefik.yaml
