apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-helmchartconfig.yaml
  - traefik-dashboard-service.yaml
  - traefik-dashboard-middleware.yaml
  - traefik-netbird-service.yaml
  - traefik-dashboard-ingress.yaml
  - network-router-vpn.yaml
  - network-resource-traefik-netbird.yaml
