name: ✨ Feature Request
description: Suggest an idea for this project.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make this homelab better? Let us know!
  - type: textarea
    id: motivation
    attributes:
      label: Problem Statement / Motivation
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
