apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-sample-from-vault
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-kubernetes
    kind: ClusterSecretStore
  target:
    name: eso-sample-synced
    creationPolicy: Owner
  data:
    - secretKey: msg
      remoteRef:
        key: cluster-defaults/sample
        property: msg
