apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-kubernetes
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-dev-root-token
          namespace: vault
          key: token
