apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgCrfSPsrD9Sdiew8+OXMeW2ecONH+xNmLLd5Z/lvpB88XbgZaMStyq6Sloo2+Ex20CXN/af9+YDnw9BkhPxBr2DyPifoUN8lWvFzftRIaehDkIrYGWbTQouZxloEjrDkNxKd90CEj7eXLn2lQ3/gQ49XgZFPWlQkowZX/h1ZYYzaDOC4CZ4jTDW1p0fVD/vCRB8i49HG47m0BuMGVNPSe6tpgWQ8XT8utDWNa+9bquuXQEl5x5inf5AjB0SUCQQWCkV8/jnrZTEmuhH9XGtRZgOvP/EHkY7A4E2xOo17Wy/cQjjmyi8f906FTNKisowTVGUf6Gq87EnM/AbQr5Lx5NC8nauqQwpC5vcINNDhD5Fz6ySDowhJFxI7a36OrK30k34drx4YXIJkRCRIvG/uIV029Wp9gau+Wggu+e9wYPUl0gCw0Rs+bZYjK0Po2tP/HG9ZVqZxqEkul+s1DJuSex5gI2iLhgOZzUjxDcT/cWWcHRHMHLNbpeIiFhGF3iNFNOFL0TuJoZiviWExeXBVp5kzVaeL+SeDPzJLh1iyny+7zFNsCY9DFCSSb2NLtU4NkN8wrzyOXV13uXzCbKfS4SAEUZW/ShSBgih0xk4gEbrrRizaTDmraC5w8NUMSJ9x1yIQVXqkXaPjXadESRAarTVfEeqTX+XsQmaBMX0oeRX3okj5vSciQ04WTKXU0OseaQZ0zn5Wi6gtEdk9dLuL9S2BniK86zQr3hj8UV3RczssNBhHCI2Sr5s
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
