apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgAhGQRa9mgoWFvcEJ6Bnibe+zjneheofQIWWH/VpQjMre9v0qwhxQeaAbXuRYpuLMBg/8IVGPnCJ+oQpyDFrkQGyLgrKTWoTBgUMBFFuQKn5Ztbm6ut/Zp4LKrx3A7CmrxOr0uNjnZ9co6R5cp5EeeUO5h96q1bmXXaWyGHz+P9RwHdKbMqRmtKG4IsbHxGJ1LjmeE9hO3RLa2mu0+MJdrKvFYKsMfh8Q6Rwdgmo+skw4bKCjwBdvEskr0o9O90P+BqOepIRD+qzNQVKOJl1v/GIKYZ9Dy+QQnBXSluVQLoPhtDlczMn30nelWtXASczuoKIa3PgTFhm+1qPOKAcxhoacBgab5YNK52ubCXayo2WlgXjj7WqE6T9ix+s9kqKJLtJnzWCutqRoR3LtQBWWQzMkm1iQVHopyhz3OsVl2AMXTG+ET+neCGG5e1zUBsA6yQPJXqeIbym7YbrlWC5Q/iI4OSj9l+991SiMmeiiFWfItan7vQf3KB4Y3iF2WRBNjg8n9t4tcUQ5ehgp4kgImgBXp8bIa6HATUhhvueq5igElPIulbm47sETQIx2q7wVU8UfLR6cSzjEtNzgcLX4gkOF7Wd9OgERfMh/X1O46gICAriQe4H5URzBePUH2hb/DO9bB+cNBZ/xiCJx2c2l2+PB0tSL1KXdAFJoWjisnWWc1fMQVTkM33k7/LP2jOIfc0WZAbRtqPFPmFJPn+DiP4Zc0D3C7vcmR4lSK7B9beLvVh3+U=
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
