apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgA+Gj0SkF2Awk3Rzk636m5xxr1McxPtGsNs2BxeHIjrG3qjL7bXTOEDyOr5xIB5u8aj10spcKC30UG1/SkeQselU7/WBRphV/2In/dEOjdBypwDJvG2EV1IgS+cJx0+J0tJ1EARVxZjxNoAT69t7OKOxtL7fYKhjxYK7hAoKTq5JJnP5DI0uskCVEq/YSqo7CfjWImnFAuFi8n5+Wc5q6SSmdOhhuPfguFA7Gm7CGTwlZ+swJwaum/WDQq6xNGhgB4aOi1jWzOEGC0uzL5UqQionw73e5XsQpPKDHA1CSEaJ08EYtYWBwv1Pl9xpqDOxgOTYHXMCZ/HI966tihGK6nk4mCFrWkb4Bd3o+q5Qqt5EenXNVq5RkcH4jdngTopJWYImksavf2Bi/EdlzGP9vCLQDfrhxsEifzS7fuMgTSkXta/fRv2gYchy1D3MUM4jMUet06VgPWS2KQO9w6skN5rZXeFmjoJbfRYmqu/2lxqCXzsTL21gdq3SXIen2FZz1Mkz44uE88ajTM/ERkxPm+G5j17QmWVSvZ54IEvw5EKJRWLNEs3cfUVnVoyvSpvmQHJwCQTPXekvTvwoK73L2RypKbz9Syi0f0GSP7FQZhL1bEuQZZ+CRhzt9UM+/MMmS40RUlwcAgIEq6sbf9M/dVvgkPWaxqr1bxm7jNCvjyZ0ZAjUU+jmj4MLWYYC4YqxhBn4o+DBxJmjENadXht+JxI0yOqhaL8xFe7aORyuQ3QQcVg6ws=
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
