# docker-compose.yaml
version: '3.7'
services:
  swarm-cd:
    image: ghcr.io/m-adawi/swarm-cd:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    secrets:
      - source: age
        target: /secrets/age.key
    environment:
      - SOPS_AGE_KEY_FILE=/secrets/age.key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./repos.yml:/app/repos.yaml:ro
      - ./stacks.yml:/app/stacks.yaml:ro
      - ./config.yml:/app/config.yaml:ro
secrets:
  age:
    file: age.key
